language: cpp
sudo: true
before_install:
  # Install GTest
  - sudo apt-get install libgtest-dev

  # Run Reneral ESP8266 install script
  - source <(curl -SLs https://raw.githubusercontent.com/Protoneer/Travis-CI-ESP8266-Initializer/master/install.sh)

  # Install PubSubClient
  - wget https://github.com/Imroy/pubsubclient/archive/v1.99.1.tar.gz -O pubsubclient.tar.gz
  - tar xf pubsubclient.tar.gz
  - mv pubsubclient-1.99.1 $HOME/arduino_ide/libraries
  - mv $HOME/arduino_ide/libraries/pubsubclient-1.99.1 $HOME/arduino_ide/libraries/pubsubclient

  # Install NeoPixels Bus
  - git clone https://github.com/Makuna/NeoPixelBus.git
  - mv NeoPixelBus $HOME/arduino_ide/libraries
  - ls $HOME/arduino_ide/libraries
  - ls ~
  - ls ~/Arduino
  - ls ~/.arduino15
  - ls ~/.arduino15/packages
  - ls ~/.arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries
  - ls $HOME/arduino_ide/libraries/pubsubclient
  - ls $HOME/arduino_ide/libraries/pubsubclient/src

  
script:
  # Set Board
  - arduino --board esp8266:esp8266:generic --save-prefs
  
  # GTests
  - sudo mkdir _builds
  - cd _builds
  - ls ..
  - sudo cmake ..
  - ls
  - sudo make
  - sudo ctest
  

  
notifications:
  email:
    on_success: change
    on_failure: change
