language: cpp
sudo: true
before_install:
  # Install GTest
  - sudo apt-get install libgtest-dev

  # Run Reneral ESP8266 install script
  - source <(curl -SLs https://raw.githubusercontent.com/Protoneer/Travis-CI-ESP8266-Initializer/master/install.sh)
  
script:
  # Set Board
  - arduino --board esp8266:esp8266:generic --save-prefs

  
notifications:
  email:
    on_success: change
    on_failure: change
